from create_app.initializer.generator import Generator


def test_branded_starter_templates_render(tmp_path):
    ctx = {
        "project_name": "demo_api",
        "framework": "fastapi",
        "fw_name": "fastapi",
        "build_strategy": "standard",
        "ui_folder": "ui",
        "port": "8000",
        "host": "0.0.0.0",
        "APP_NAME": "init-app",
        "APP_TAGLINE": "High-Performance System & Native Extension Generator",
        "version": "3.1.0",
        "DEFAULT_PORTS": {"fastapi": "8000"},
    }
    generator = Generator(tmp_path, ctx)

    generator._render_and_write("common/entry.py.tpl", "app.py")
    generator._render_and_write("common/template/index.html.tpl", "ui/index.html")
    generator._render_and_write("common/static/css/style.css.tpl", "ui/static/css/style.css")

    app_py = (tmp_path / "app.py").read_text()
    index = (tmp_path / "ui" / "index.html").read_text()
    css = (tmp_path / "ui" / "static" / "css" / "style.css").read_text()

    assert "Generated by init-app" in app_py
    assert "def missing_dependency(package_name):" in app_py
    assert "python -m pip install -r requirements.txt" in app_py
    assert "@app.get(\"/health\")" in app_py
    assert "@app.get(\"/api/about\")" in app_py
    assert "generated by init-app" in index
    assert "init-app v3.1.0" in index
    assert "Backend First" in index
    assert "body.fastapi" in css


def test_starter_app_uses_project_relative_ui_paths(tmp_path):
    ctx = {
        "project_name": "portable_api",
        "framework": "fastapi",
        "fw_name": "fastapi",
        "build_strategy": "standard",
        "ui_folder": "ui",
        "port": "8000",
        "host": "0.0.0.0",
        "APP_NAME": "init-app",
        "APP_TAGLINE": "High-Performance System & Native Extension Generator",
                "version": "3.1.0",
        "DEFAULT_PORTS": {"fastapi": "8000"},
    }
    generator = Generator(tmp_path, ctx)

    generator._render_and_write("common/entry.py.tpl", "app.py")

    app_py = (tmp_path / "app.py").read_text()
    assert "BASE_DIR = Path(__file__).resolve().parent" in app_py
    assert "UI_PATH = BASE_DIR / UI_FOLDER" in app_py
    assert "StaticFiles(directory=str(UI_PATH / \"static\"))" in app_py


def test_supported_starter_apps_render_valid_python(tmp_path):
    frameworks = [
        ("fastapi", "ui", "8000"),
        ("flask", "templates", "5000"),
        ("bottle", "templates", "8080"),
        ("sanic", "ui", "8000"),
        ("falcon", "ui", "8000"),
        ("tornado", "ui", "8888"),
        ("pyramid", "ui", "6543"),
        ("base", "ui", "8000"),
        ("hp_cli", "ui", "8000"),
        ("data_pipeline", "ui", "8000"),
        ("dbt_analytics", "ui", "8000"),
    ]

    for framework, ui_folder, port in frameworks:
        project_root = tmp_path / framework
        ctx = {
            "project_name": f"{framework}_demo",
            "framework": framework,
            "fw_name": framework,
            "build_strategy": "standard",
            "ui_folder": ui_folder,
            "port": port,
            "host": "0.0.0.0",
            "APP_NAME": "init-app",
            "APP_TAGLINE": "High-Performance System & Native Extension Generator",
            "version": "3.1.0",
            "DEFAULT_PORTS": {framework: port},
        }
        generator = Generator(project_root, ctx)
        generator._render_and_write("common/entry.py.tpl", "app.py")

        app_py = project_root / "app.py"
        compile(app_py.read_text(), str(app_py), "exec")
