from create_app.initializer.generator import Generator


def test_branded_starter_templates_render(tmp_path):
    ctx = {
        "project_name": "demo_api",
        "framework": "fastapi",
        "fw_name": "fastapi",
        "build_strategy": "standard",
        "ui_folder": "ui",
        "port": "8000",
        "host": "0.0.0.0",
        "APP_NAME": "init-app",
        "APP_TAGLINE": "High-Performance System & Native Extension Generator",
        "version": "2.2.0b2",
        "DEFAULT_PORTS": {"fastapi": "8000"},
    }
    generator = Generator(tmp_path, ctx)

    generator._render_and_write("common/entry.py.tpl", "app.py")
    generator._render_and_write("common/template/index.html.tpl", "ui/index.html")
    generator._render_and_write("common/static/css/style.css.tpl", "ui/static/css/style.css")

    app_py = (tmp_path / "app.py").read_text()
    index = (tmp_path / "ui" / "index.html").read_text()
    css = (tmp_path / "ui" / "static" / "css" / "style.css").read_text()

    assert "Generated by init-app" in app_py
    assert "def missing_dependency(package_name):" in app_py
    assert "python -m pip install -r requirements.txt" in app_py
    assert "@app.get(\"/health\")" in app_py
    assert "@app.get(\"/api/about\")" in app_py
    assert "generated by init-app" in index
    assert "init-app v2.2.0b2" in index
    assert "Backend First" in index
    assert "body.fastapi" in css


def test_starter_app_uses_project_relative_ui_paths(tmp_path):
    ctx = {
        "project_name": "portable_api",
        "framework": "fastapi",
        "fw_name": "fastapi",
        "build_strategy": "standard",
        "ui_folder": "ui",
        "port": "8000",
        "host": "0.0.0.0",
        "APP_NAME": "init-app",
        "APP_TAGLINE": "High-Performance System & Native Extension Generator",
        "version": "2.2.0b2",
        "DEFAULT_PORTS": {"fastapi": "8000"},
    }
    generator = Generator(tmp_path, ctx)

    generator._render_and_write("common/entry.py.tpl", "app.py")

    app_py = (tmp_path / "app.py").read_text()
    assert "BASE_DIR = Path(__file__).resolve().parent" in app_py
    assert "UI_PATH = BASE_DIR / UI_FOLDER" in app_py
    assert "StaticFiles(directory=str(UI_PATH / \"static\"))" in app_py
