"""
{{ project_name }} - {{ fw_name | upper }} starter server
Generated by {{ APP_NAME }} v{{ version }}
"""

import json
import os
import sys
from pathlib import Path


PROJECT_NAME = "{{ project_name }}"
FRAMEWORK = "{{ fw_name }}"
BUILD_STRATEGY = "{{ build_strategy }}"
APP_BRAND = "{{ APP_NAME }}"
APP_VERSION = "{{ version }}"
HOST = "{{ host | default('0.0.0.0') }}"
PORT = {{ port if (port and port != 'na') else 8000 }}
UI_FOLDER = "{{ ui_folder | default('ui') }}"
BASE_DIR = Path(__file__).resolve().parent
UI_PATH = BASE_DIR / UI_FOLDER


def missing_dependency(package_name):
    print(f"\nMissing dependency: {package_name}")
    print("Install the generated project requirements first:")
    print("  python -m pip install -r requirements.txt\n")
    sys.exit(1)


def project_meta():
    return {
        "name": PROJECT_NAME,
        "framework": FRAMEWORK,
        "strategy": BUILD_STRATEGY,
        "status": "online",
        "generated_by": APP_BRAND,
        "generator_version": APP_VERSION,
    }


def index_html():
    page = UI_PATH / "index.html"
    if page.exists():
        return page.read_text(encoding="utf-8")

    return (
        "<!doctype html><html><head><title>"
        + PROJECT_NAME
        + "</title></head><body><h1>"
        + PROJECT_NAME
        + "</h1><p>Generated by "
        + APP_BRAND
        + ".</p></body></html>"
    )


{% if fw_name == 'fastapi' %}
try:
    from fastapi import FastAPI
    from fastapi.responses import HTMLResponse
    from fastapi.staticfiles import StaticFiles
except ModuleNotFoundError as exc:
    missing_dependency(exc.name)

app = FastAPI(title=PROJECT_NAME, version="0.1.0")

if (UI_PATH / "static").exists():
    app.mount("/static", StaticFiles(directory=str(UI_PATH / "static")), name="static")


@app.get("/", response_class=HTMLResponse)
async def home():
    return index_html()


@app.get("/health")
async def health():
    return {"status": "online", "framework": FRAMEWORK}


@app.get("/api/about")
async def about():
    return project_meta()


{% elif fw_name == 'flask' %}
try:
    from flask import Flask, jsonify, render_template
except ModuleNotFoundError as exc:
    missing_dependency(exc.name)

app = Flask(__name__, template_folder=str(UI_PATH), static_folder=str(UI_PATH / "static"))


@app.route("/")
def home():
    return render_template("index.html")


@app.route("/health")
def health():
    return jsonify({"status": "online", "framework": FRAMEWORK})


@app.route("/api/about")
def about():
    return jsonify(project_meta())


{% elif fw_name == 'bottle' %}
try:
    from bottle import Bottle, response, run, static_file, template
except ModuleNotFoundError as exc:
    missing_dependency(exc.name)

app = Bottle()


@app.route("/static/<path:path>")
def serve_static(path):
    return static_file(path, root=str(UI_PATH / "static"))


@app.route("/")
def home():
    return template(str(UI_PATH / "index.html"))


@app.route("/health")
def health():
    response.content_type = "application/json"
    return json.dumps({"status": "online", "framework": FRAMEWORK})


@app.route("/api/about")
def about():
    response.content_type = "application/json"
    return json.dumps(project_meta())


{% elif fw_name == 'sanic' %}
try:
    from sanic import Sanic, response
except ModuleNotFoundError as exc:
    missing_dependency(exc.name)

app = Sanic(PROJECT_NAME)

if (UI_PATH / "static").exists():
    app.static("/static", str(UI_PATH / "static"))


@app.get("/")
async def home(request):
    return response.html(index_html())


@app.get("/health")
async def health(request):
    return response.json({"status": "online", "framework": FRAMEWORK})


@app.get("/api/about")
async def about(request):
    return response.json(project_meta())


{% elif fw_name == 'tornado' %}
try:
    import tornado.ioloop
    import tornado.web
except ModuleNotFoundError as exc:
    missing_dependency(exc.name)


class MainHandler(tornado.web.RequestHandler):
    def get(self):
        self.write(index_html())


class HealthHandler(tornado.web.RequestHandler):
    def get(self):
        self.write({"status": "online", "framework": FRAMEWORK})


class AboutHandler(tornado.web.RequestHandler):
    def get(self):
        self.write(project_meta())


def make_app():
    return tornado.web.Application(
        [
            (r"/", MainHandler),
            (r"/health", HealthHandler),
            (r"/api/about", AboutHandler),
            (r"/static/(.*)", tornado.web.StaticFileHandler, {"path": str(UI_PATH / "static")}),
        ]
    )


{% elif fw_name == 'falcon' %}
from wsgiref.simple_server import make_server

try:
    import falcon
except ModuleNotFoundError as exc:
    missing_dependency(exc.name)


class HomeResource:
    def on_get(self, req, resp):
        resp.content_type = "text/html"
        resp.text = index_html()


class HealthResource:
    def on_get(self, req, resp):
        resp.media = {"status": "online", "framework": FRAMEWORK}


class AboutResource:
    def on_get(self, req, resp):
        resp.media = project_meta()


app = falcon.App()
app.add_route("/", HomeResource())
app.add_route("/health", HealthResource())
app.add_route("/api/about", AboutResource())


{% elif fw_name == 'pyramid' %}
try:
    from waitress import serve
    from pyramid.config import Configurator
    from pyramid.response import Response
except ModuleNotFoundError as exc:
    missing_dependency(exc.name)


def home(request):
    return Response(index_html(), content_type="text/html")


def health(request):
    return Response(json.dumps({"status": "online", "framework": FRAMEWORK}), content_type="application/json")


def about(request):
    return Response(json.dumps(project_meta()), content_type="application/json")


with Configurator() as config:
    config.add_route("home", "/")
    config.add_view(home, route_name="home")
    config.add_route("health", "/health")
    config.add_view(health, route_name="health")
    config.add_route("about", "/api/about")
    config.add_view(about, route_name="about")
    app = config.make_wsgi_app()


{% elif fw_name == 'django' %}
try:
    from django.core.management import execute_from_command_line
except ModuleNotFoundError as exc:
    missing_dependency(exc.name)

os.environ.setdefault("DJANGO_SETTINGS_MODULE", "{{ project_name }}.settings")


{% else %}
from http.server import SimpleHTTPRequestHandler, ThreadingHTTPServer


class StarterHandler(SimpleHTTPRequestHandler):
    def do_GET(self):
        if self.path == "/health":
            self._json({"status": "online", "framework": FRAMEWORK})
            return
        if self.path == "/api/about":
            self._json(project_meta())
            return
        if self.path == "/":
            content = index_html().encode("utf-8")
            self.send_response(200)
            self.send_header("Content-Type", "text/html; charset=utf-8")
            self.send_header("Content-Length", str(len(content)))
            self.end_headers()
            self.wfile.write(content)
            return
        super().do_GET()

    def _json(self, payload):
        content = json.dumps(payload).encode("utf-8")
        self.send_response(200)
        self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", str(len(content)))
        self.end_headers()
        self.wfile.write(content)


app = None
{% endif %}


if __name__ == "__main__":
    print(f"\n{APP_BRAND} starter ready")
    print(f"Project   : {PROJECT_NAME}")
    print(f"Framework : {FRAMEWORK}")
    print(f"URL       : http://{HOST}:{PORT}")
    print(f"Health    : http://{HOST}:{PORT}/health\n")

{% if fw_name == 'fastapi' or fw_name == 'sanic' %}
    try:
        import uvicorn
    except ModuleNotFoundError as exc:
        missing_dependency(exc.name)

    uvicorn.run(app, host=HOST, port=PORT)
{% elif fw_name == 'flask' %}
    app.run(host=HOST, port=PORT, debug=True)
{% elif fw_name == 'bottle' %}
    run(app, host=HOST, port=PORT, debug=True)
{% elif fw_name == 'tornado' %}
    make_app().listen(PORT, address=HOST)
    tornado.ioloop.IOLoop.current().start()
{% elif fw_name == 'falcon' %}
    with make_server(HOST, PORT, app) as server:
        server.serve_forever()
{% elif fw_name == 'pyramid' %}
    serve(app, host=HOST, port=PORT)
{% elif fw_name == 'django' %}
    execute_from_command_line([sys.argv[0], "runserver", f"{HOST}:{PORT}"])
{% else %}
    ThreadingHTTPServer((HOST, PORT), StarterHandler).serve_forever()
{% endif %}
