# {{ project_name }}

Generated by **{{ APP_NAME }}** v{{ version }}.

## Overview

`{{ project_name }}` is a {{ framework }} application scaffolded in `{{ build_strategy }}` mode. It includes a basic branded landing page, a health endpoint, an API identity endpoint, and a ready-to-run server entrypoint.

Project path:

```text
{{ project_path }}
```

## Included Routes

| Route | Purpose |
| --- | --- |
| `/` | Branded starter page |
| `/health` | Backend health response |
| `/api/about` | Project and generator metadata |
{% if framework == 'fastapi' %}| `/docs` | FastAPI OpenAPI documentation |
{% endif %}

## Run Locally

```bash
python -m venv venv
```

macOS / Linux:

```bash
source venv/bin/activate
```

Windows:

```powershell
venv\Scripts\activate
```

Install dependencies:

```bash
python -m pip install --upgrade pip
python -m pip install -r requirements.txt
```

The generated requirements are designed for clean dev, CI, and container environments. MySQL projects use `PyMySQL` by default instead of `mysqlclient`, avoiding native `pkg-config` and system-header build failures.

Start the server:

```bash
{% if framework == 'django' %}
python manage.py runserver
{% else %}
python app.py
{% endif %}
```

## Project Notes

- Framework: `{{ framework }}`
- Strategy: `{{ build_strategy }}`
- Output directory: `{{ output_dir }}`
- Created from: `{{ invocation_dir }}`
- Generated by: `{{ APP_NAME }}`
