<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{ project_name }} | {{ APP_NAME }}</title>
    <meta name="description" content="{{ project_name }} generated by {{ APP_NAME }}">
    <link rel="stylesheet" href="/static/css/style.css">
    <script>
        (function () {
            var key = "{{ project_name | lower }}-theme";
            var saved = localStorage.getItem(key);
            var prefersDark = window.matchMedia("(prefers-color-scheme: dark)").matches;
            document.documentElement.dataset.theme = saved || (prefersDark ? "dark" : "light");
        }());
    </script>
</head>
<body class="app-shell {{ framework }}">
    <header class="topbar">
        <a class="brand" href="/" aria-label="{{ project_name }} home">
            <span class="brand-mark">ia</span>
            <span>
                <strong>{{ project_name }}</strong>
                <small>generated by {{ APP_NAME }}</small>
            </span>
        </a>

        <nav class="nav-links" aria-label="Primary navigation">
            <a href="/health">Health</a>
            <a href="/api/about">API</a>
            {% if framework == 'fastapi' %}
            <a href="/docs">Docs</a>
            {% endif %}
            <button id="theme-toggle" class="icon-button" type="button" aria-label="Toggle theme">
                <span></span>
            </button>
        </nav>
    </header>

    <main class="hero">
        <section class="hero-copy">
            <p class="eyebrow">{{ framework | capitalize }} backend starter</p>
            <h1>{{ project_name }} is ready to build.</h1>
            <p class="lead">
                A clean backend foundation with a branded landing page, health endpoint,
                API identity route, and production-minded project structure.
            </p>

            <div class="actions">
                <a class="button primary" href="/health">Check health</a>
                <a class="button secondary" href="/api/about">View API identity</a>
            </div>
        </section>

        <section class="status-panel" aria-label="Application status">
            <div class="status-header">
                <span class="pulse"></span>
                <span>Server online</span>
            </div>

            <dl class="metrics">
                <div>
                    <dt>Framework</dt>
                    <dd>{{ framework | capitalize }}</dd>
                </div>
                <div>
                    <dt>Mode</dt>
                    <dd>{{ build_strategy | capitalize }}</dd>
                </div>
                <div>
                    <dt>Port</dt>
                    <dd>{{ DEFAULT_PORTS.get(framework, "8000") }}</dd>
                </div>
                <div>
                    <dt>Generator</dt>
                    <dd>{{ APP_NAME }} v{{ version }}</dd>
                </div>
            </dl>

            <pre class="terminal"><code>GET /health
{
  "status": "online",
  "framework": "{{ framework }}"
}</code></pre>
        </section>
    </main>

    <section class="feature-band" aria-label="Included foundation">
        <article>
            <h2>Backend First</h2>
            <p>Routes, health checks, dependency files, and a server entrypoint are ready from the first run.</p>
        </article>
        <article>
            <h2>Branded Base</h2>
            <p>Every generated app carries a consistent init-app identity without hiding your project name.</p>
        </article>
        <article>
            <h2>Modern Defaults</h2>
            <p>Responsive UI, accessible controls, dark/light theme, and clean static asset paths.</p>
        </article>
    </section>

    <footer class="footer">
        <span>{{ project_name }}</span>
        <span>{{ APP_TAGLINE }}</span>
    </footer>

    <script src="/static/js/script.js"></script>
</body>
</html>
